#!/usr/bin/env python3
"""
PowerPoint Presentation Generator
Creates .pptx files from content outlines
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import json
import os

def create_ppt(title, slides, output_path):
    """
    Create PowerPoint presentation
    
    Args:
        title: Presentation title
        slides: List of slide dictionaries
            Each slide: {
                'title': str,
                'content': list of str,
                'notes': str (optional)
            }
        output_path: Path to save .pptx file
    """
    prs = Presentation()
    
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_placeholder = slide.shapes.title
    subtitle_placeholder = slide.placeholders[1]
    
    title_placeholder.text = title
    subtitle_placeholder.text = f"Generated by Chat | {len(slides)} slides"
    
    # Content slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    for slide_data in slides:
        slide = prs.slides.add_slide(bullet_slide_layout)
        
        # Set title
        title_placeholder = slide.shapes.title
        title_placeholder.text = slide_data['title']
        
        # Set content
        body_placeholder = slide.placeholders[1]
        tf = body_placeholder.text_frame
        tf.clear()  # Clear default paragraph
        
        for i, point in enumerate(slide_data['content']):
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            
            p.text = point
            p.font.size = Pt(18)
            p.level = 0
            
            # Add sub-bullets if content has "  -" prefix
            if point.startswith('  -'):
                p.level = 1
                p.text = point.replace('  -', '')
        
        # Add speaker notes if provided
        if 'notes' in slide_data:
            notes_slide = slide.notes_slide
            notes_slide.notes_text_frame.text = slide_data['notes']
    
    # Save presentation
    prs.save(output_path)
    print(f"✅ Presentation created: {output_path}")
    print(f"   Slides: {len(slides) + 1}")  # +1 for title slide
    
    return output_path


def create_ppt_from_json(json_path, output_path=None):
    """Create PPT from JSON file"""
    
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    if not output_path:
        output_path = json_path.replace('.json', '.pptx')
    
    return create_ppt(
        title=data.get('title', 'Presentation'),
        slides=data.get('slides', []),
        output_path=output_path
    )


# Example usage
if __name__ == '__main__':
    # Example content
    example_ppt = {
        'title': 'AI 时代的人类认知重构',
        'slides': [
            {
                'title': '核心问题',
                'content': [
                    'AI 如何重新定义人类智能？',
                    '教育的目标需要如何改变？',
                    '创造力的边界在哪里？'
                ],
                'notes': '开场问题，引发思考'
            },
            {
                'title': '智能的边界',
                'content': [
                    '传统智能定义面临挑战',
                    '机器智能的优势领域',
                    '人类智能的独特价值'
                ]
            },
            {
                'title': '教育重构',
                'content': [
                    '从知识传授到能力培养',
                    '批判性思维的重要性',
                    '终身学习成为必需'
                ]
            },
            {
                'title': '总结',
                'content': [
                    '拥抱变化，保持学习',
                    '人机协作是未来',
                    '人类价值在于创造力'
                ]
            }
        ]
    }
    
    # Save example JSON
    example_path = '/Users/tomchen/.openclaw/workspace-chat/kanban-board/temp/example-ppt.json'
    with open(example_path, 'w', encoding='utf-8') as f:
        json.dump(example_ppt, f, ensure_ascii=False, indent=2)
    
    # Create PPT
    output_path = '/Users/tomchen/.openclaw/workspace-chat/kanban-board/temp/example-ppt.pptx'
    create_ppt_from_json(example_path, output_path)
