#!/usr/bin/env python3
"""
Test PowerPoint Generation
演示 powerpoint-pptx 技能
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

def create_demo_ppt(output_path):
    """创建演示 PPT"""
    
    prs = Presentation()
    
    # Slide 1: 标题页
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "OpenClaw 文件管理能力演示"
    subtitle.text = "PowerPoint + Dropbox 集成\nGenerated by Chat"
    
    # Slide 2: 功能概览
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "核心功能"
    
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.text = "PowerPoint PPTX 技能"
    
    p = tf.add_paragraph()
    p.text = "专业 PPT 生成"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "支持多种布局"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "图表和表格支持"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "模板自动化"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = ""
    
    p = tf.add_paragraph()
    p.text = "Dropbox 集成"
    p.level = 0
    
    p = tf.add_paragraph()
    p.text = "云端文件存储"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "安全分享链接"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "大文件传输（2GB+）"
    p.level = 1
    
    # Slide 3: 使用场景
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "使用场景"
    
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.text = "场景 1：制作演示文稿"
    
    p = tf.add_paragraph()
    p.text = "你提供主题 → 我生成 PPT → 本地获取或上传 Dropbox"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = ""
    
    p = tf.add_paragraph()
    p.text = "场景 2：文件传输"
    p.level = 0
    
    p = tf.add_paragraph()
    p.text = "上传文件给我 → 我处理 → 上传 Dropbox → 返回分享链接"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = ""
    
    p = tf.add_paragraph()
    p.text = "场景 3：批量处理"
    p.level = 0
    
    p = tf.add_paragraph()
    p.text = "多个文件 → 统一处理 → 批量上传 → 生成索引"
    p.level = 1
    
    # Slide 4: 下一步
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "现在开始使用"
    
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.text = "1. 告诉我 PPT 主题和内容"
    
    p = tf.add_paragraph()
    p.text = "我会生成专业幻灯片"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = ""
    
    p = tf.add_paragraph()
    p.text = "2. 配置 Dropbox（可选）"
    p.level = 0
    
    p = tf.add_paragraph()
    p.text = "按照 docs/dropbox-setup.md 配置"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "获取云端存储和分享能力"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = ""
    
    p = tf.add_paragraph()
    p.text = "3. 开始使用！"
    p.level = 0
    
    # 保存
    prs.save(output_path)
    print(f"✅ 演示 PPT 已创建：{output_path}")
    print(f"   幻灯片数：{len(prs.slides)}")
    
    return output_path

if __name__ == '__main__':
    output = '/Users/tomchen/.openclaw/workspace-chat/kanban-board/temp/demo-ppt.pptx'
    create_demo_ppt(output)
